apiVersion: v1
kind: Service
metadata:
  name:  nginx-service
spec:
  selector:
    app:  nginx
  # type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  8080